# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 15070181343
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 80
lzzzs:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
